version: "3.5"

services:
  admin:
    stdin_open: true
    image: node:12
    volumes:
      - ./admin:/usr/src/admin
    environment:
      REACT_APP_API_ENTRYPOINT: http://vulcain:80
    ports:
      - 3000:3000
    working_dir: /usr/src/admin
    command: yarn start

  cypress:
    image: cypress/browsers:chrome69
    user: "${UID}:${GID}"
    ipc: host
    depends_on:
      - admin
      - vulcain
      - api
    volumes:
      - ./tests:/app
    environment:
      - CYPRESS_CACHE_FOLDER=/app/var/cypress_cache
    working_dir: /app
    links:
      - "admin:admin"
      - "vulcain:vulcain"
    command: yarn run tests
